# Generated by Django 4.2.3 on 2023-09-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('erp_Id', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pin', models.PositiveBigIntegerField(max_length=20)),
                ('Phone', models.PositiveBigIntegerField()),
                ('Vdiscountpercent', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Popsstrata', models.CharField(max_length=100)),
                ('Businesstype', models.CharField(max_length=100)),
                ('Warehouse_Type', models.CharField(max_length=100)),
                ('Warehouse_Category', models.CharField(max_length=100)),
                ('Prefix_To_Billno', models.CharField(max_length=100)),
                ('Suffix_To_Billno', models.CharField(max_length=100)),
                ('Prefix_To_Creditno', models.CharField(max_length=100)),
                ('Suffix_To_Creditno', models.CharField(max_length=100)),
                ('Prefix_To_Debitno', models.CharField(max_length=100)),
                ('Suffix_To_Debitno', models.CharField(max_length=100)),
                ('Prefix_To_Salereturnno', models.CharField(max_length=100)),
                ('Suffix_To_Salereturnno', models.CharField(max_length=100)),
                ('Prefix_Challan_Number', models.CharField(max_length=100)),
                ('Suffix_Challan_Number', models.CharField(max_length=100)),
                ('Warehouse_Label', models.CharField(max_length=100)),
                ('Default_Credit_Limit', models.CharField(max_length=100)),
                ('Default_Credit_Period', models.CharField(max_length=100)),
                ('Default_Minimum_Order_Value', models.CharField(max_length=100)),
                ('Subzone', models.CharField(max_length=100)),
                ('Parent_Warehouse', models.CharField(max_length=100)),
                ('Currency', models.CharField(max_length=100)),
                ('QR_Code_Image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('Warehouse_TIN', models.CharField(max_length=100)),
                ('PAN_no', models.CharField(max_length=100)),
                ('FSSAI_no', models.CharField(max_length=100)),
                ('Warehouse_CST', models.CharField(max_length=100)),
                ('GSTIN', models.CharField(max_length=100)),
                ('Warehouse_LBT_no', models.CharField(max_length=100)),
                ('Jurisdiction', models.CharField(max_length=100)),
                ('Country_WMS', models.CharField(max_length=100)),
                ('Tenant_WMS', models.CharField(max_length=100)),
                ('Category_WMS', models.CharField(max_length=100)),
                ('Address_type_WMS', models.CharField(max_length=100)),
                ('Address_line2_WMS', models.CharField(max_length=100)),
                ('Status_WMS', models.CharField(max_length=100)),
                ('Zone_code_WMS', models.CharField(max_length=100)),
                ('Lat_WMS', models.CharField(max_length=100)),
                ('Long_WMS', models.CharField(max_length=100)),
            ],
        ),
    ]
